version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:18.18.2
    steps:
      - checkout
      - restore_cache:
          keys: [backend-build]
      - run:
          name: setup
          command: |
            cd backend
            make setup
      - run:
          name: install dependencies
          command: |
            cd backend
            make install
      - run:
          name: run test
          command: |
            cd backend
            make test
      - run:
          name: run lint
          command: |
            cd backend
            make lint
      - save_cache:
          paths: [backend/node_modules]
          key: backend-build

workflows:
  default:
    jobs:
      - build